### ISSUE TITLE
socks.SOCKS5Error: 0x06: TTL expired

### ISSUE THREAD

**Issue by chefarov** [ahmia/ahmia-crawler#10]
After fixing #9 this came up, seems like a PySocks bug: #todo report it. 

```

Exception happened during processing of request from ('127.0.0.1', 48068)
Traceback (most recent call last):
  File "<path2venv>/ahmia-crawler/lib/python3.6/site-packages/socks.py", line 851, in connect
    negotiate(self, dest_addr, dest_port)
  File "<path2venv>/ahmia-crawler/lib/python3.6/site-packages/socks.py", line 497, in _negotiate_SOCKS5
    self, CONNECT, dest_addr)
  File "<path2venv>/ahmia-crawler/lib/python3.6/site-packages/socks.py", line 578, in _SOCKS5_request
    raise SOCKS5Error("{0:#04x}: {1}".format(status, error))
socks.SOCKS5Error: 0x06: TTL expired
```

Currently `polipo` remains the stable proxy solution for the crawler.

**Comment by chefarov** [comment]
Deprecated by `torfleet`, new native python tor proxy
