### ISSUE TITLE
scripts of type [inline], operation [update] and lang [groovy] are disabled'

### ISSUE THREAD

**Issue by ShaliDaliHaliDa** [ahmia/ahmia-crawler#4]
Anyone seen this before?

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapyelasticsearch/scrapyelasticsearch.py", line 116, in process_item
    self.index_item(item)
  File "/home/akent/Desktop/ahmia-crawler/ahmia/ahmia/pipelines.py", line 87, in index_item
    self.send_items()
  File "/usr/local/lib/python2.7/dist-packages/scrapyelasticsearch/scrapyelasticsearch.py", line 109, in send_items
    helpers.bulk(self.es, self.items_buffer)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 190, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 134, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
BulkIndexError: (u'316 document(s) failed to index.', [{u'update': {u'status': 400, u'_type': u'tor', u'_id': u'd3ba376d34cbea850dabc25b1d4a884da852c995', u'error': {u'caused_by': {u'reason': u'scripts of type [inline], operation [update] and lang [groovy] are disabled', u'type': u'script_exception'}, u'reason': u'failed to execute script', u'type': u'illegal_argument_exception'}, u'_index': u'crawl'}}, {u'update': {u'status': 400, u'_type': u'tor', u'_id': u'9bbd33851fb71cc9980b262797a00c1a06932094', u'error': {u'caused_by': {u'reason': u'scripts of type [inline], operation [update] and lang [groovy] are disabled', u'type': u'script_exception'}, u'reason': u'failed to execute script', u'type': u'illegal_argument_exception'}, u'_index': u'crawl'}}, {u'update': {u'status': 400, u'_type': u'tor', u'_id': u'd730f4a540adad5892aa58a5870baed904b6c4c1', u'error': {u'caused_by': {u'reason': u'sc

**Comment by iriahi** [comment]
I think you need to update your elasticsearch config file as described [here](https://github.com/ahmia/ahmia-index/) (in the /etc/elasticsearch/elasticsearch.yml section).
