### ISSUE TITLE
TorSocks proxy throws: unexpected keyword argument 'fileno'

### ISSUE THREAD

**Issue by chefarov** [ahmia/ahmia-crawler#9]
```
$ python http_tor_proxy.py 
Serving at port 14444
```

```
$ curl -x http://localhost:14444 http://msydqstlz2kzerdg.onion
Traceback (most recent call last):
  File "http_tor_proxy.py", line 67, in <module>
    httpd.serve_forever()
  File "/usr/lib/python3.6/socketserver.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python3.6/socketserver.py", line 312, in _handle_request_noblock
    request, client_address = self.get_request()
  File "/usr/lib/python3.6/socketserver.py", line 500, in get_request
    return self.socket.accept()
  File "/usr/lib/python3.6/socket.py", line 210, in accept
    sock = socket(self.family, type, self.proto, fileno=fd)
TypeError: __init__() got an unexpected keyword argument 'fileno'
```

**Comment by chefarov** [comment]
reinstalling `PySocks==1.6.8` at the same version fixes this ...
